### PR TITLE
Add completion suggestions for global event scripts

### PR DESCRIPTION
**Pull request by BigBahss**
Typing into the `Script` combo-box will now suggest all global event scripts, in addition to the map's scripts. Expanding the combo-box will still only show the map's scripts since showing a huge list of global scripts isn't very convenient.

### CODE REVIEW

**Comment by huderlem** [comment]
I'm noticing a small bug where selecting an event object and typing in a script (but not finalizing it?) duplicates or insert it into the available autocompletion options.  As you can see here, there are a bunch of extra option from when I was typing in the "FatMan" script.
image

**Comment by BigBahss** [comment]
Interesting, I'll look into that. (Also I misclicked to close lol).

**Comment by garakmon** [comment]
Any interest in revisiting this? The issue mentioned above seems like it could be fixed by changing the insert policy to NoInsert for the combobox.

**Comment by BigBahss** [comment]
I was putting off revisiting this because I started working on another project, but I'll try what you have suggested. Thanks for looking into that.

**Comment by BigBahss** [comment]
Fixed

**Pull request merged**
