### PR TITLE
Tileset workflow

### PR DESCRIPTION
**Pull request by SBird1337**
Add a quick dialog to add a new tileset, create it with a dummy image and dummy metatiles for later on editing.

Although this does not touch the mapgroups, it resolves part of #64.

Feedback appreciated.

### CODE REVIEW

**Comment by huderlem** [comment]
A few things that need to be addressed:
1. I was able to create two identically-named tilesets `gTileset_Foo` by creating one as a primary and the other as a secondary.  The duplicate name check needs to extend to all tilesets--not just the primary or secondary sets.
2. Can you add ellipses to "New Map" and "New Tileset" menu options? ("New Map..." and "New Tileset...")
3. In the error message for "tileset already exists", include the name of the tileset.  Something like "Tileset 'gTileset_Foo' already exists".
4. Either show a success message after the tileset has been created, or set the current map's tileset to the newly-created tileset.
5. The New Map window is completely broken.  Did you accidentally change that file?  Seems like it shouldn't have been touched by this PR.

**Comment by SBird1337** [comment]
Those should be fixed, I also added a keyboard shortcut (CTRL+SHIFT+N).

**Comment by SBird1337** [comment]
Changed this to WIP, when compiling the tilesets seem to be broken in-game. Currently I have no idea of why that happens, granted it worked before, too.

**Comment by SBird1337** [comment]
The process works fine now, the serialization just misaligned the padding, see 91be88e.

**Pull request merged**
