### PR TITLE
Wild Encounters Editing

### PR DESCRIPTION
**Pull request by garakmon**
I tried to make this user-friendly and as accommodating as possible to different changes people may want to make. I hope I was successful.

Working on documentation now before I forget all of the stuff I added.

### CODE REVIEW

**Comment by garakmon** [comment]
whoops
TODO: add config option to disable for those who don't want to use JSON for encounters

**Comment by huderlem** [comment]
forgot about this. will review tonight

**Comment by SBird1337** [comment]
Some things I noticed:
image

* long names are not ideal (See Screenshot)
* UX for adding new groups that do not exist yet is not really intuitive (Maybe add a tab anyways and create a button there, or at least add a note/tooltip that say "Right Clickt to add" or something

**Comment by SBird1337** [comment]
Newly created tabs do not correctly show "0" for the encounter rate:
image
Also the label should probably say "%"

**Pull request merged**
