### PR TITLE
Flip Full Selection In Tileset Editor

### PR DESCRIPTION
**Pull request by garakmon**
gif

### CODE REVIEW

**Comment by huderlem** [comment]
I just noticed a regression when painting a greater than 1x1 selection onto the Bottom/Top layers.  If I click on the bottom-right corner tile of the Bottom layer, then it paints like this:
image

It looks like this is also a problem in the `master` branch, but maybe you could try and fix that now if it's easy.

**Comment by garakmon** [comment]
is the intended behavior to just draw the top-left corner of the selection onto that corner?

**Comment by huderlem** [comment]
It's intended to only draw the top row of the tile selection in this case.  So, just the top of the sign.

**Comment by garakmon** [comment]
oh "of the bottom layer"

**Comment by garakmon** [comment]
I'm 99.9% sure it is fixed now, I messed around a bunch with it and it seems to work as intended.

**Pull request merged**
